version: "3.7"

services:

  postgres:
    build:
      context: "./database"
      dockerfile: Dockerfile
    container_name: postgres_cqrs
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "cqrs"
    restart: always
    ports:
      - "54321:5432"

  nats:
    image: "nats-streaming:0.9.2"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200

  feed:
    build:
      context: "."
      dockerfile: Dockerfile
    command: [ 'feed-service' ]
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "cqrs"
      NATS_ADDRESS: "nats:4222"
  
  query: 
    build: "."
    command: [ 'query-service' ]
    depends_on:
      - "postgres"
      - "nats"
      - "elasticsearch"
    ports:
      - "8080"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "cqrs"
      NATS_ADDRESS: "nats:4222"
      ELASTIC_SEARCH_ADDR: "elasticsearch:9200"
  
  pusher:
    build: "."
    command: [ 'pusher-service' ]
    depends_on:
      - "nats"
    ports:
      - "8080"
    environment:
      NATS_ADDRESS: "nats:4222"

  nginx:
    build: "./nginx"
    ports:
      - "8080:80"
    depends_on:
      - feed
      - query
      - pusher